name: Performance & SEO CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      env:
        NEXT_PUBLIC_SITE_URL: https://hyperhash.ai
        NEXT_PUBLIC_API_URL: https://hyperhash-production-2512.up.railway.app
        
    - name: Start server
      run: npm start &
      env:
        PORT: 3000
        
    - name: Wait for server
      run: npx wait-on http://localhost:3000 --timeout 60000
      
    - name: Run Lighthouse CI
      run: |
        npm install -g @lhci/cli@0.12.x
        lhci autorun
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        
    - name: Upload Lighthouse results
      uses: actions/upload-artifact@v3
      with:
        name: lighthouse-results
        path: .lighthouseci/reports/
        
  seo-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Check sitemap
      run: |
        if [ -f ".next/server/app/sitemap.xml/route.js" ]; then
          echo "✅ Sitemap route exists"
        else
          echo "❌ Sitemap route missing"
          exit 1
        fi
        
    - name: Check robots.txt
      run: |
        if [ -f ".next/server/app/robots.txt/route.js" ]; then
          echo "✅ Robots.txt route exists"
        else
          echo "❌ Robots.txt route missing"
          exit 1
        fi
        
    - name: Validate meta tags
      run: |
        npm run lint
        echo "✅ SEO validation complete"
        
  build-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Type check
      run: npx tsc --noEmit
      
    - name: Lint
      run: npm run lint
      
    - name: Build
      run: npm run build
      
    - name: Check bundle size
      run: |
        npm install -g bundlesize
        echo "Checking bundle sizes..."
        # Add bundle size checks here
